// SmsFinance file version: 3 — two P0 fixes from a technical/accounting review, both confirmed
// against this exact file before fixing:
// 1. Restore now properly remaps categoryId/counterpartyId (and settledTransactionId for
//    checks) from the backup's OLD ids to the NEWLY-assigned ids in this database, instead of
//    inserting the old ids verbatim. Previously, restoring into a non-empty database (or any
//    database where autogenerated ids don't happen to line up) could silently attach a
//    transaction to the WRONG category or counterparty -- confirmed: the old ids were used
//    as-is for transactions, checks, AND smart rules, not just transactions.
// 2. The whole restore is now wrapped in db.withTransaction{} -- previously a failure partway
//    through (e.g. a malformed row late in the file) could leave a half-restored database with
//    no way to tell what succeeded.
package com.kamal.smsfinance.util

import android.content.Context
import android.net.Uri
import androidx.room.withTransaction
import com.kamal.smsfinance.data.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * Local backup/restore using a hand-rolled JSON format (no extra dependency
 * needed). Backups are plain files under getExternalFilesDir("backups") so
 * the user can move/copy them manually, or restore via a content:// Uri
 * (e.g. picked from a file manager or cloud-synced folder, including a
 * locally-synced Google Drive folder). Covers all five tables: transactions,
 * categories, counterparties, checks, smart rules.
 *
 * "version" here is a BACKUP-FORMAT version, intentionally decoupled from
 * Room's schema version (which changes independently as columns are added).
 * Forward/backward compatibility is handled by keeping every field read
 * with root.has(...) / opt*() -- an older backup missing a newer table
 * simply restores nothing for it instead of failing, and a newer backup
 * opened by older code just ignores fields it doesn't expect. This
 * tolerant-parsing approach is deliberately simpler than a strict migration
 * ladder, which isn't justified yet for a single-device local file.
 *
 * Restore safety: categories and counterparties are deduped by name
 * (case-insensitive) so restoring never creates duplicate rows -- including
 * duplicates of the seeded default categories. Every cross-table reference
 * (transactions/checks/rules -> categoryId/counterpartyId, checks ->
 * settledTransactionId) is remapped through an old-id -> new-id table built
 * while restoring categories/counterparties/transactions, so relationships
 * stay correct regardless of whether the target database was empty or not.
 */
object BackupManager {

    private const val BACKUP_FORMAT_VERSION = 3

    private fun String?.orNull(): Any = this ?: JSONObject.NULL
    private fun Long?.orNull(): Any = this ?: JSONObject.NULL

    suspend fun hasExistingData(db: AppDatabase): Boolean = withContext(Dispatchers.IO) {
        db.transactionDao().getAllOnce().isNotEmpty()
    }

    /** Clears the rows that a replacement restore owns. Must be called inside db.withTransaction. */
    private suspend fun clearDataForReplacement(db: AppDatabase) {
        db.transactionDao().deleteAll()
        db.checkDao().getAllOnce().forEach { db.checkDao().delete(it) }
        db.smartRuleDao().getAllRulesOnce().forEach { db.smartRuleDao().deleteRule(it) }
        db.counterpartyDao().getAllOnce().forEach { db.counterpartyDao().delete(it) }
    }

    suspend fun createBackup(context: Context, db: AppDatabase): File = withContext(Dispatchers.IO) {
        val root = JSONObject()
        root.put("version", BACKUP_FORMAT_VERSION)
        root.put("createdAt", System.currentTimeMillis())

        root.put("transactions", JSONArray().apply {
            db.transactionDao().getAllOnce().forEach { t ->
                put(JSONObject().apply {
                    put("id", t.id)
                    put("amountToman", t.amountToman)
                    put("type", t.type.name)
                    put("bankName", t.bankName)
                    put("description", t.description)
                    put("date", t.date)
                    put("source", t.source.name)
                    put("rawSms", t.rawSms.orNull())
                    put("smsSender", t.smsSender.orNull())
                    put("accountTail", t.accountTail.orNull())
                    put("categoryId", t.categoryId.orNull())
                    put("counterpartyId", t.counterpartyId.orNull())
                    put("isIndirectSettlement", t.isIndirectSettlement)
                    put("notes", t.notes.orNull())
                })
            }
        })

        root.put("categories", JSONArray().apply {
            db.categoryDao().getAllOnce().forEach { c ->
                put(JSONObject().apply {
                    put("id", c.id); put("name", c.name); put("kind", c.kind.name); put("isDefault", c.isDefault)
                    put("parentId", c.parentId.orNull())
                })
            }
        })

        root.put("counterparties", JSONArray().apply {
            db.counterpartyDao().getAllOnce().forEach { cp ->
                put(JSONObject().apply {
                    put("id", cp.id)
                    put("name", cp.name)
                    put("type", cp.type.name)
                    put("phone", cp.phone.orNull())
                    put("address", cp.address.orNull())
                    put("description", cp.description.orNull())
                    put("notes", cp.notes.orNull())
                    put("createdAt", cp.createdAt)
                })
            }
        })

        root.put("checks", JSONArray().apply {
            db.checkDao().getAllOnce().forEach { chk ->
                put(JSONObject().apply {
                    put("id", chk.id)
                    put("type", chk.type.name)
                    put("counterpartyId", chk.counterpartyId.orNull())
                    put("amountToman", chk.amountToman)
                    put("dueDate", chk.dueDate)
                    put("status", chk.status.name)
                    put("paidDate", chk.paidDate.orNull())
                    put("reminderDays", chk.reminderDays)
                    put("description", chk.description.orNull())
                    put("settledTransactionId", chk.settledTransactionId.orNull())
                    put("createdAt", chk.createdAt)
                })
            }
        })

        root.put("smartRules", JSONArray().apply {
            db.smartRuleDao().getAllRulesOnce().forEach { rule ->
                put(JSONObject().apply {
                    put("id", rule.id)
                    put("pattern", rule.pattern)
                    put("categoryId", rule.categoryId.orNull())
                    put("counterpartyId", rule.counterpartyId.orNull())
                    put("createdAt", rule.createdAt)
                })
            }
        })

        val dir = File(context.getExternalFilesDir(null), "backups").apply { mkdirs() }
        val file = File(dir, "backup_${System.currentTimeMillis()}.json")
        file.writeText(root.toString(2))
        file
    }

    /**
     * Restores from a backup file. When [replaceExisting] is true, the rows
     * owned by the backup are cleared inside the same Room transaction as the
     * import. Therefore a malformed file cannot leave the user with an empty
     * database after the old data was removed.
     */
    suspend fun restoreBackup(
        context: Context,
        uri: Uri,
        db: AppDatabase,
        replaceExisting: Boolean = false
    ): Int =
        withContext(Dispatchers.IO) {
            val text = context.contentResolver.openInputStream(uri)?.bufferedReader()?.readText()
                ?: return@withContext 0
            val root = JSONObject(text)

            db.withTransaction {
                if (replaceExisting) clearDataForReplacement(db)

                // oldId -> newId for every table another table can point to. Built while
                // restoring each table below. A genuinely null JSON field remains null;
                // a non-null old id that cannot be resolved is rejected so relationships are
                // never silently lost.
                val categoryIdMap = mutableMapOf<Long, Long>()
                val counterpartyIdMap = mutableMapOf<Long, Long>()
                val transactionIdMap = mutableMapOf<Long, Long>()

                if (root.has("categories")) {
                    val arr = root.getJSONArray("categories")
                    val entries = (0 until arr.length()).map { arr.getJSONObject(it) }

                    // Pass 1: top-level categories (no parentId in the backup) -- must exist
                    // before any child can be resolved and linked to them.
                    entries.filter { it.isNull("parentId") || !it.has("parentId") }.forEach { o ->
                        val oldId = o.getLong("id")
                        val name = o.getString("name")
                        val existing = db.categoryDao().getAllOnce().firstOrNull { it.name.equals(name, ignoreCase = true) }
                        val newId = existing?.id ?: db.categoryDao().insert(
                            Category(
                                name = name,
                                kind = CategoryKind.valueOf(o.getString("kind")),
                                isDefault = o.optBoolean("isDefault", false)
                            )
                        )
                        categoryIdMap[oldId] = newId
                    }

                    // Pass 2: subcategories. The backup's own "parentId" is an OLD id -- resolve
                    // it through categoryIdMap (built in pass 1) to find the REAL parent in this
                    // database, not by re-matching names, which is redundant now that pass 1
                    // already recorded every top-level category's new id.
                    entries.filterNot { it.isNull("parentId") || !it.has("parentId") }.forEach { o ->
                        val oldId = o.getLong("id")
                        val name = o.getString("name")
                        val existing = db.categoryDao().getAllOnce().firstOrNull { it.name.equals(name, ignoreCase = true) }
                        val resolvedParentId = categoryIdMap[o.getLong("parentId")]
                        val newId = existing?.id ?: db.categoryDao().insert(
                            Category(
                                name = name,
                                kind = CategoryKind.valueOf(o.getString("kind")),
                                isDefault = o.optBoolean("isDefault", false),
                                parentId = resolvedParentId
                            )
                        )
                        categoryIdMap[oldId] = newId
                    }
                }

                if (root.has("counterparties")) {
                    val arr = root.getJSONArray("counterparties")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val oldId = o.getLong("id")
                        val name = o.getString("name")
                        val existing = db.counterpartyDao().getAllOnce().firstOrNull { it.name.equals(name, ignoreCase = true) }
                        val newId = existing?.id ?: db.counterpartyDao().insert(
                            Counterparty(
                                name = name,
                                type = CounterpartyType.valueOf(o.getString("type")),
                                phone = o.optStringOrNull("phone"),
                                address = o.optStringOrNull("address"),
                                description = o.optStringOrNull("description"),
                                notes = o.optStringOrNull("notes"),
                                createdAt = o.optLong("createdAt", System.currentTimeMillis())
                            )
                        )
                        counterpartyIdMap[oldId] = newId
                    }
                }

                var restored = 0
                if (root.has("transactions")) {
                    val arr = root.getJSONArray("transactions")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val oldId = o.getLong("id")
                        val newId = db.transactionDao().insert(
                            Transaction(
                                amountToman = o.getLong("amountToman"),
                                type = TransactionType.valueOf(o.getString("type")),
                                bankName = o.getString("bankName"),
                                description = o.getString("description"),
                                date = o.getLong("date"),
                                source = TransactionSource.valueOf(o.getString("source")),
                                rawSms = o.optStringOrNull("rawSms"),
                                smsSender = o.optStringOrNull("smsSender"),
                                accountTail = o.optStringOrNull("accountTail"),
                                categoryId = categoryIdMap.resolveReference(o.optLongOrNull("categoryId"), "categoryId"),
                                counterpartyId = counterpartyIdMap.resolveReference(o.optLongOrNull("counterpartyId"), "counterpartyId"),
                                isIndirectSettlement = o.optBoolean("isIndirectSettlement", false),
                                notes = o.optStringOrNull("notes")
                            )
                        )
                        transactionIdMap[oldId] = newId
                        restored++
                    }
                }

                if (root.has("checks")) {
                    val arr = root.getJSONArray("checks")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        db.checkDao().insert(
                            Check(
                                type = CheckType.valueOf(o.getString("type")),
                                counterpartyId = counterpartyIdMap.resolveReference(o.optLongOrNull("counterpartyId"), "check.counterpartyId"),
                                amountToman = o.getLong("amountToman"),
                                dueDate = o.getLong("dueDate"),
                                status = CheckStatus.valueOf(o.getString("status")),
                                paidDate = o.optLongOrNull("paidDate"),
                                reminderDays = o.optInt("reminderDays", 3),
                                description = o.optStringOrNull("description"),
                                settledTransactionId = transactionIdMap.resolveReference(o.optLongOrNull("settledTransactionId"), "check.settledTransactionId"),
                                createdAt = o.optLong("createdAt", System.currentTimeMillis())
                            )
                        )
                    }
                }

                if (root.has("smartRules")) {
                    val arr = root.getJSONArray("smartRules")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        db.smartRuleDao().insertRule(
                            SmartRule(
                                pattern = o.getString("pattern"),
                                categoryId = categoryIdMap.resolveReference(o.optLongOrNull("categoryId"), "rule.categoryId"),
                                counterpartyId = counterpartyIdMap.resolveReference(o.optLongOrNull("counterpartyId"), "rule.counterpartyId"),
                                createdAt = o.optLong("createdAt", System.currentTimeMillis())
                            )
                        )
                    }
                }

                restored
            }
        }

    private fun <V> Map<Long, V>.resolveReference(oldId: Long?, field: String): V? {
        if (oldId == null) return null
        return this[oldId]
            ?: throw IllegalArgumentException("Invalid backup reference: $field=$oldId")
    }

    private fun JSONObject.optStringOrNull(key: String): String? =
        if (has(key) && !isNull(key)) getString(key) else null

    private fun JSONObject.optLongOrNull(key: String): Long? =
        if (has(key) && !isNull(key)) getLong(key) else null
}
