// SmsFinance file version: 3 — two P0 fixes from a technical/accounting review, both confirmed
// against this exact file before fixing:
// 1. Restore now properly remaps categoryId/counterpartyId (and settledTransactionId for
//    checks) from the backup's OLD ids to the NEWLY-assigned ids in this database, instead of
//    inserting the old ids verbatim. Previously, restoring into a non-empty database (or any
//    database where autogenerated ids don't happen to line up) could silently attach a
//    transaction to the WRONG category or counterparty -- confirmed: the old ids were used
//    as-is for transactions, checks, AND smart rules, not just transactions.
// 2. The whole restore is now wrapped in db.withTransaction{} -- previously a failure partway
//    through (e.g. a malformed row late in the file) could leave a half-restored database with
//    no way to tell what succeeded.
package com.kamal.smsfinance.util

import android.content.Context
import android.net.Uri
import androidx.room.withTransaction
import com.kamal.smsfinance.data.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * Local backup/restore using a hand-rolled JSON format (no extra dependency
 * needed). Backups are plain files under getExternalFilesDir("backups") so
 * the user can move/copy them manually, or restore via a content:// Uri
 * (e.g. picked from a file manager or cloud-synced folder, including a
 * locally-synced Google Drive folder). Covers six tables: transactions,
 * categories, counterparties, counterparty reminders, checks and smart rules.
 *
 * "version" here is a BACKUP-FORMAT version, intentionally decoupled from
 * Room's schema version (which changes independently as columns are added).
 * Forward/backward compatibility is handled by keeping every field read
 * with root.has(...) / opt*() -- an older backup missing a newer table
 * simply restores nothing for it instead of failing, and a newer backup
 * opened by older code just ignores fields it doesn't expect. This
 * tolerant-parsing approach is deliberately simpler than a strict migration
 * ladder, which isn't justified yet for a single-device local file.
 *
 * Restore safety: categories and counterparties are deduped by name
 * (case-insensitive) so restoring never creates duplicate rows -- including
 * duplicates of the seeded default categories. Every cross-table reference
 * (transactions/checks/rules -> categoryId/counterpartyId, checks ->
 * settledTransactionId, transactions -> linkedCheckId, reminders -> counterpartyId) is remapped through old-id -> new-id tables built
 * while restoring categories/counterparties/transactions, so relationships
 * stay correct regardless of whether the target database was empty or not.
 */
object BackupManager {

    private const val BACKUP_FORMAT_VERSION = 4

    private fun String?.orNull(): Any = this ?: JSONObject.NULL
    private fun Long?.orNull(): Any = this ?: JSONObject.NULL

    suspend fun hasExistingData(db: AppDatabase): Boolean = withContext(Dispatchers.IO) {
        db.transactionDao().getAllOnce().isNotEmpty()
    }

    /** Wipes everything a restore would repopulate, EXCEPT categories (deduped by name instead, so user-added custom categories aren't lost). */
    suspend fun wipeForRestore(db: AppDatabase) = withContext(Dispatchers.IO) {
        db.transactionDao().deleteAll()
        db.counterpartyReminderDao().getAllOnce().forEach { db.counterpartyReminderDao().delete(it) }
        db.counterpartyDao().getAllOnce().forEach { db.counterpartyDao().delete(it) }
        db.checkDao().getAllOnce().forEach { db.checkDao().delete(it) }
        db.smartRuleDao().getAllRulesOnce().forEach { db.smartRuleDao().deleteRule(it) }
    }

    suspend fun createBackup(context: Context, db: AppDatabase): File = withContext(Dispatchers.IO) {
        val root = JSONObject()
        root.put("version", BACKUP_FORMAT_VERSION)
        root.put("createdAt", System.currentTimeMillis())

        root.put("transactions", JSONArray().apply {
            db.transactionDao().getAllOnce().forEach { t ->
                put(JSONObject().apply {
                    put("id", t.id)
                    put("amountToman", t.amountToman)
                    put("type", t.type.name)
                    put("bankName", t.bankName)
                    put("description", t.description)
                    put("date", t.date)
                    put("source", t.source.name)
                    put("rawSms", t.rawSms.orNull())
                    put("smsSender", t.smsSender.orNull())
                    put("accountTail", t.accountTail.orNull())
                    put("categoryId", t.categoryId.orNull())
                    put("counterpartyId", t.counterpartyId.orNull())
                    put("isIndirectSettlement", t.isIndirectSettlement)
                    put("transferGroupId", t.transferGroupId.orNull())
                    put("linkedCheckId", t.linkedCheckId.orNull())
                    put("notes", t.notes.orNull())
                })
            }
        })

        root.put("categories", JSONArray().apply {
            db.categoryDao().getAllOnce().forEach { c ->
                put(JSONObject().apply {
                    put("id", c.id); put("name", c.name); put("kind", c.kind.name); put("isDefault", c.isDefault)
                    put("parentId", c.parentId.orNull())
                })
            }
        })

        root.put("counterparties", JSONArray().apply {
            db.counterpartyDao().getAllOnce().forEach { cp ->
                put(JSONObject().apply {
                    put("id", cp.id)
                    put("name", cp.name)
                    put("type", cp.type.name)
                    put("phone", cp.phone.orNull())
                    put("address", cp.address.orNull())
                    put("description", cp.description.orNull())
                    put("notes", cp.notes.orNull())
                    put("createdAt", cp.createdAt)
                })
            }
        })

        root.put("checks", JSONArray().apply {
            db.checkDao().getAllOnce().forEach { chk ->
                put(JSONObject().apply {
                    put("id", chk.id)
                    put("type", chk.type.name)
                    put("counterpartyId", chk.counterpartyId.orNull())
                    put("amountToman", chk.amountToman)
                    put("dueDate", chk.dueDate)
                    put("status", chk.status.name)
                    put("paidDate", chk.paidDate.orNull())
                    put("reminderDays", chk.reminderDays)
                    put("description", chk.description.orNull())
                    put("settledTransactionId", chk.settledTransactionId.orNull())
                    put("createdAt", chk.createdAt)
                })
            }
        })

        root.put("counterpartyReminders", JSONArray().apply {
            db.counterpartyReminderDao().getAllOnce().forEach { reminder ->
                put(JSONObject().apply {
                    put("id", reminder.id)
                    put("counterpartyId", reminder.counterpartyId)
                    put("title", reminder.title)
                    put("details", reminder.details.orNull())
                    put("dueAt", reminder.dueAt.orNull())
                    put("isDone", reminder.isDone)
                    put("createdAt", reminder.createdAt)
                    put("completedAt", reminder.completedAt.orNull())
                })
            }
        })

        root.put("smartRules", JSONArray().apply {
            db.smartRuleDao().getAllRulesOnce().forEach { rule ->
                put(JSONObject().apply {
                    put("id", rule.id)
                    put("pattern", rule.pattern)
                    put("categoryId", rule.categoryId.orNull())
                    put("counterpartyId", rule.counterpartyId.orNull())
                    put("createdAt", rule.createdAt)
                })
            }
        })

        val dir = File(context.getExternalFilesDir(null), "backups").apply { mkdirs() }
        val file = File(dir, "backup_${System.currentTimeMillis()}.json")
        file.writeText(root.toString(2))
        file
    }

    /**
     * Restores from a backup file. Call hasExistingData()+wipeForRestore()
     * from the caller first (with user confirmation) for a clean restore
     * into a non-empty database -- see the class doc-comment. The whole
     * restore runs inside a single database transaction: if anything throws
     * partway through, nothing from this call is left committed.
     *
     * @param wipeFirst when true, wipes transactions/counterparties/checks/rules INSIDE the
     * same transaction as the restore (ported from Hesabdary6-main rev22) -- previously the
     * caller ran wipeForRestore() as a separate call before this one, so a restore that failed
     * partway through left the database empty with no way back. Categories are still deduped
     * by name rather than wiped, same as before, so user-added custom categories survive.
     */
    /** Alias used by TransactionViewModel.performRestoreAtomic() -- wipe-then-restore as a
     * single atomic call, i.e. restoreBackup(wipeFirst = true). */
    suspend fun restoreAndReplaceAtomic(context: Context, uri: Uri, db: AppDatabase): Int =
        restoreBackup(context, uri, db, wipeFirst = true)

    suspend fun restoreBackup(context: Context, uri: Uri, db: AppDatabase, wipeFirst: Boolean = false): Int =
        withContext(Dispatchers.IO) {
            val text = context.contentResolver.openInputStream(uri)?.bufferedReader()?.readText()
                ?: return@withContext 0
            val root = JSONObject(text)

            db.withTransaction {
                if (wipeFirst) {
                    db.transactionDao().deleteAll()
                    db.counterpartyDao().getAllOnce().forEach { db.counterpartyDao().delete(it) }
                    db.checkDao().getAllOnce().forEach { db.checkDao().delete(it) }
                    db.smartRuleDao().getAllRulesOnce().forEach { db.smartRuleDao().deleteRule(it) }
                }

                // oldId -> newId for every table another table can point to. Built while
                // restoring each table below; a lookup with a null result (no entry, or the
                // JSON field itself was null) resolves to null, which is a valid "no
                // category/counterparty/settlement" state rather than an error.
                val categoryIdMap = mutableMapOf<Long, Long>()
                val counterpartyIdMap = mutableMapOf<Long, Long>()
                val transactionIdMap = mutableMapOf<Long, Long>()
                val checkIdMap = mutableMapOf<Long, Long>()
                val transferGroupIdMap = mutableMapOf<Long, Long>()

                if (root.has("categories")) {
                    val arr = root.getJSONArray("categories")
                    val pending = (0 until arr.length()).map { arr.getJSONObject(it) }.toMutableList()

                    // Resolve parents level by level. This supports arbitrary depth instead of
                    // assuming that every category is either a root or a direct child.
                    while (pending.isNotEmpty()) {
                        val sizeBefore = pending.size
                        val iterator = pending.iterator()
                        while (iterator.hasNext()) {
                            val o = iterator.next()
                            val oldId = o.getLong("id")
                            val oldParentId = o.optLongOrNull("parentId")
                            if (oldParentId != null && !categoryIdMap.containsKey(oldParentId)) continue

                            val name = o.getString("name")
                            val kind = CategoryKind.valueOf(o.getString("kind"))
                            val existing = db.categoryDao().getAllOnce().firstOrNull {
                                it.name.equals(name, ignoreCase = true) && it.kind == kind &&
                                    it.parentId == oldParentId?.let { parent -> categoryIdMap[parent] }
                            }
                            val newId = existing?.id ?: db.categoryDao().insert(
                                Category(
                                    name = name,
                                    kind = kind,
                                    isDefault = o.optBoolean("isDefault", false),
                                    parentId = oldParentId?.let { parent -> categoryIdMap[parent] }
                                )
                            )
                            if (newId > 0) {
                                categoryIdMap[oldId] = newId
                                iterator.remove()
                            }
                        }

                        // A malformed/cyclic backup must not block all remaining data. The
                        // unresolved node is restored as a root, with its original id mapped.
                        if (pending.size == sizeBefore) {
                            val o = pending.removeAt(0)
                            val oldId = o.getLong("id")
                            val newId = db.categoryDao().insert(
                                Category(
                                    name = o.getString("name"),
                                    kind = CategoryKind.valueOf(o.getString("kind")),
                                    isDefault = o.optBoolean("isDefault", false),
                                    parentId = null
                                )
                            )
                            categoryIdMap[oldId] = newId
                        }
                    }
                }

                if (root.has("counterparties")) {
                    val arr = root.getJSONArray("counterparties")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val oldId = o.getLong("id")
                        val name = o.getString("name")
                        val existing = db.counterpartyDao().getAllOnce().firstOrNull { it.name.equals(name, ignoreCase = true) }
                        val newId = existing?.id ?: db.counterpartyDao().insert(
                            Counterparty(
                                name = name,
                                type = CounterpartyType.valueOf(o.getString("type")),
                                phone = o.optStringOrNull("phone"),
                                address = o.optStringOrNull("address"),
                                description = o.optStringOrNull("description"),
                                notes = o.optStringOrNull("notes"),
                                createdAt = o.optLong("createdAt", System.currentTimeMillis())
                            )
                        )
                        counterpartyIdMap[oldId] = newId
                    }
                }

                var restored = 0
                if (root.has("transactions")) {
                    val arr = root.getJSONArray("transactions")
                    val oldTransferGroups = (0 until arr.length())
                        .mapNotNull { arr.getJSONObject(it).optLongOrNull("transferGroupId") }
                        .distinct()
                    val occupiedTransferGroups = db.transactionDao().getAllOnce()
                        .mapNotNull { it.transferGroupId }
                        .toSet()
                    transferGroupIdMap.putAll(
                        TransferGroupIdRemapper.createMapping(
                            oldGroupIds = oldTransferGroups,
                            occupiedGroupIds = occupiedTransferGroups,
                            firstCandidate = System.currentTimeMillis()
                        )
                    )
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val oldId = o.getLong("id")
                        val newId = db.transactionDao().insert(
                            Transaction(
                                amountToman = o.getLong("amountToman"),
                                type = TransactionType.valueOf(o.getString("type")),
                                bankName = o.getString("bankName"),
                                description = o.getString("description"),
                                date = o.getLong("date"),
                                source = TransactionSource.valueOf(o.getString("source")),
                                rawSms = o.optStringOrNull("rawSms"),
                                smsSender = o.optStringOrNull("smsSender"),
                                accountTail = o.optStringOrNull("accountTail"),
                                categoryId = o.optLongOrNull("categoryId")?.let { categoryIdMap[it] },
                                counterpartyId = o.optLongOrNull("counterpartyId")?.let { counterpartyIdMap[it] },
                                isIndirectSettlement = o.optBoolean("isIndirectSettlement", false),
                                transferGroupId = o.optLongOrNull("transferGroupId")?.let { transferGroupIdMap[it] },
                                // linkedCheckId is applied after checks are restored and remapped.
                                linkedCheckId = null,
                                notes = o.optStringOrNull("notes")
                            )
                        )
                        transactionIdMap[oldId] = newId
                        restored++
                    }
                }

                if (root.has("checks")) {
                    val arr = root.getJSONArray("checks")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val newCheckId = db.checkDao().insert(
                            Check(
                                type = CheckType.valueOf(o.getString("type")),
                                counterpartyId = o.optLongOrNull("counterpartyId")?.let { counterpartyIdMap[it] },
                                amountToman = o.getLong("amountToman"),
                                dueDate = o.getLong("dueDate"),
                                status = CheckStatus.valueOf(o.getString("status")),
                                paidDate = o.optLongOrNull("paidDate"),
                                reminderDays = o.optInt("reminderDays", 3),
                                description = o.optStringOrNull("description"),
                                settledTransactionId = o.optLongOrNull("settledTransactionId")?.let { transactionIdMap[it] },
                                createdAt = o.optLong("createdAt", System.currentTimeMillis())
                            )
                        )
                        checkIdMap[o.getLong("id")] = newCheckId
                    }
                }

                // Checks are inserted after transactions, so restore the transaction -> check
                // links only after both old-id maps are complete.
                if (root.has("transactions")) {
                    val arr = root.getJSONArray("transactions")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val newTransactionId = transactionIdMap[o.getLong("id")]
                        val newCheckId = o.optLongOrNull("linkedCheckId")?.let { checkIdMap[it] }
                        if (newTransactionId != null && newCheckId != null) {
                            db.transactionDao().linkCheck(newTransactionId, newCheckId)
                        }
                    }
                }

                if (root.has("counterpartyReminders")) {
                    val arr = root.getJSONArray("counterpartyReminders")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        val counterpartyId = counterpartyIdMap[o.getLong("counterpartyId")] ?: continue
                        db.counterpartyReminderDao().insert(
                            CounterpartyReminder(
                                counterpartyId = counterpartyId,
                                title = o.getString("title"),
                                details = o.optStringOrNull("details"),
                                dueAt = o.optLongOrNull("dueAt"),
                                isDone = o.optBoolean("isDone", false),
                                createdAt = o.optLong("createdAt", System.currentTimeMillis()),
                                completedAt = o.optLongOrNull("completedAt")
                            )
                        )
                    }
                }

                if (root.has("smartRules")) {
                    val arr = root.getJSONArray("smartRules")
                    for (i in 0 until arr.length()) {
                        val o = arr.getJSONObject(i)
                        db.smartRuleDao().insertRule(
                            SmartRule(
                                pattern = o.getString("pattern"),
                                categoryId = o.optLongOrNull("categoryId")?.let { categoryIdMap[it] },
                                counterpartyId = o.optLongOrNull("counterpartyId")?.let { counterpartyIdMap[it] },
                                createdAt = o.optLong("createdAt", System.currentTimeMillis())
                            )
                        )
                    }
                }

                restored
            }
        }

    private fun JSONObject.optStringOrNull(key: String): String? =
        if (has(key) && !isNull(key)) getString(key) else null

    private fun JSONObject.optLongOrNull(key: String): Long? =
        if (has(key) && !isNull(key)) getLong(key) else null
}
